### ISSUE TITLE
Enable Webcam Access for ThinLinc Client

### ISSUE THREAD

**Issue by richusony** [cendio/ansible-role-thinlinc-server#41]
It would be highly beneficial if the ThinLinc client could have access to the webcam. This feature would enhance the user experience by allowing video functionalities within remote sessions, such as video conferencing and camera-based applications.

Enabling webcam access would align with the growing need for seamless remote work capabilities and could greatly improve usability in various scenarios.

**Comment by samhed** [comment]
Agreed, it would be very nice. This github project isn't the right place to discuss it though.

I'd recommend heading over to our community. For example, there's this thread where one user is attempting to build his own webcam solution for ThinLinc:

https://community.thinlinc.com/t/video-forwarding/903

If you're interested in keeping track of official webcam support in ThinLinc, see our Bugzilla:

https://bugzilla.cendio.com/show_bug.cgi?id=2068
