### ISSUE TITLE
Thinlinc single node "cluster"

### ISSUE THREAD

**Issue by pewo** [cendio/ansible-role-thinlinc-server#6]
I'm trying to deploy some single node cluster with this playbook. 
The only way i manage to this is by having an inventory file like

```
[thinlinc_masters]
myserver.foo.com

[thinlinc_agents]
127.0.0.1

[thinlinc_servers:children]
thinlinc_masters
thinlinc_agents
```

And I execute my playbook with the above inventory file but limited to only myserver.foo.com
```
# ansible-playbook thinlinc.yml -i inventory/thinlinc-myserver.foo.com -l myserver.foo.com
```
If possible it should be nice to have the role, understand/support if the server in thinlinc_masters and thinlinc_agents are the same server. Setup a single node cluster. I think the problem with current role, is the configuration of agents in vsmagent.conf. Should be 127.0.0.1 instead of myserver.foo.com.

Otherwise the role work very nice!

/Peter

**Comment by samhed** [comment]
Does it work if you set `thinlinc_agent_hostname` in defaults/main.yml to myserver.foo.com as well has have myserver.foo.com in `[thinlinc_agents]` in the inventory?

**Comment by pewo** [comment]
I can try that, but does it not mean that I have to have different roles to all my single clusters ? 
(with different defaults/main.yml)

**Comment by samhed** [comment]
> does it not mean that I have to have different roles to all my single clusters ?
(with different defaults/main.yml)

I'm not sure I understand what you mean?

Anyway, you should be able to have the following inventory:

```
[thinlinc_masters]
myserver.foo.com

[thinlinc_agents]
myserver.foo.com

[thinlinc_servers:children]
thinlinc_masters
thinlinc_agents
```

What issue were you seeing when running like that?

**Comment by pewo** [comment]
Ok I misunderstood, that I have tried but it does not work.
The installation is OK but I can not connect to the cluster.
In some configurationfiles it replaces the "correct" 127.0.0.1 with myserver.foo.com
```

vsmagent.hconf:  (working)
  master_hostname=localhost                 
  allowed_clients=

vsmserver.hconf (working)
  agents=127.0.0.1


vsmagent.hconf (not working)
  master_hostname=myserver.foo.com   
  allowed_clients=myserver.foo.com


vsmserver.hconf (not working)
  agents=myserver.foo.com 

```

When trying to connect :
```
Thinlinc login failed.
(The SSH connection succeeded, but the Thinlinc server connection failed.
Perhaps this server doesn't run a Thinlinc server?)
```
The same output when trying using password, kerberos and key login.

**Comment by pewo** [comment]
Ok I misunderstood, that I have tried but it does not work.
The installation is OK but I can not connect to the cluster.
In some configurationfiles it replaces the "correct" 127.0.0.1 with myserver.foo.com
```

vsmagent.hconf:  (working)
  master_hostname=localhost                 
  allowed_clients=

vsmserver.hconf (working)
  agents=127.0.0.1


vsmagent.hconf (not working)
  master_hostname=myserver.foo.com   
  allowed_clients=myserver.foo.com


vsmserver.hconf (not working)
  agents=myserver.foo.com 

```

When trying to connect :
```
Thinlinc login failed.
(The SSH connection succeeded, but the Thinlinc server connection failed.
Perhaps this server doesn't run a Thinlinc server?)
```
The same output when trying using password, kerberos and key login.

**Comment by pewo** [comment]
Ok I misunderstood, that I have tried but it does not work.
The installation is OK but I can not connect to the cluster.
In some configurationfiles it replaces the "correct" 127.0.0.1 with myserver.foo.com
```

vsmagent.hconf:  (working)
  master_hostname=localhost                 
  allowed_clients=

vsmserver.hconf (working)
  agents=127.0.0.1


vsmagent.hconf (not working)
  master_hostname=myserver.foo.com   
  allowed_clients=myserver.foo.com


vsmserver.hconf (not working)
  agents=myserver.foo.com 

```

When trying to connect :
```
Thinlinc login failed.
(The SSH connection succeeded, but the Thinlinc server connection failed.
Perhaps this server doesn't run a Thinlinc server?)
```
The same output when trying using password, kerberos and key login.

**Comment by samhed** [comment]
Is the vsmagent service running? (Thinking of your other issue #7)
What does /var/log/vsmagent.log and /var/log/vsmserver.log say?

**Comment by pewo** [comment]
Trying to reproduce the error in my lab at home, without luck.
It works like expected, must be something with the old installation on the same machine.
